# docker run --name db-mechanics-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABAS
# E=db-mechanics-pg -p 5433:5432 docker.io/bitnami/postgresql:16  

version: "3"

#pg mechanic
services:
  db:
    image: docker.io/bitnami/postgresql:16
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/pg
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: db-mechanics-pg

  #app mechanic
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/db-mechanics-pg?schema=public
    command: [ "npm", "run", "start:deploy" ]

  # zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db_data:
