name: Run E2E Tests

on: [push]

jobs: 
    run-e2e-tests:
        name: Run E2E Tests
        runs-on: ubuntu-latest

        services:
            postgres:
              image: docker.io/bitnami/postgresql:16
              ports:
                - 5433:5432
              env:
                POSTGRES_USERNAME: docker
                POSTGRES_PASSWORD: docker
                POSTGRES_DATABASE: db-mechanics-pg
            
            zookeeper:
              image: confluentinc/cp-zookeeper:latest
              ports:
                - "2181:2181"
              env:
                  ZOOKEEPER_CLIENT_PORT: 2181
                  ZOOKEEPER_TICK_TIME: 2000

            kafka:
              image: confluentinc/cp-kafka:latest
              ports:
                - "9092:9092"
              env:
                  KAFKA_BROKER_ID: 1
                  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
                  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1      
          
        steps: 
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'

            - run: npm ci

            - run: npm run test:e2e
              env: 
                DATABASE_URL: "postgresql://docker:docker@localhost:5433/db-mechanics-pg?schema=public"

